<?php

namespace AppBundle\Repository;

/**
 * QuestionValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionValueRepository extends \Doctrine\ORM\EntityRepository
{
}
