<?php

namespace AppBundle\Repository;

/**
 * QuestionLibraryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionLibraryRepository extends \Doctrine\ORM\EntityRepository
{
}
